os: linux
dist: focal
language: ruby

stages:
 - sync

jobs:
  include:
    - name: sync
      arch: amd64
      stage: sync

      install:
        # install travis cli
        - gem install --no-document travis
        # setup travis shell autocomplete
        - echo "y" | travis --version

      script:
        - ./rickroll.sh

      if: branch = "master"
